%YAML 1.0
---
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1
num_of_cam: 2

imu_topic: "/cam_EE/imu"
image0_topic: "/cam_EE/infra1/image_rect_raw"
image1_topic: "/cam_EE/infra2/image_rect_raw"
output_path: "output/"

cam0_calib: "left_EE.yaml"
cam1_calib: "right_EE.yaml"
image_width: 1280
image_height: 720

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2: unknown, auto-calib on-fly
# [2023-04-28-10-10-32_light_EE_ir-report-imucam.pdf]
body_T_cam0: !!opencv-matrix
    rows: 4
    cols: 4
    dt: d
    data: [  0.99989603, -0.00226054, 0.01424155, -0.02286928,
             0.00221144, 0.99999156, 0.00346255, 0.00395832,
            -0.01424925, -0.0034307, 0.99989259, 0.03077921,
             0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
    rows: 4
    cols: 4
    dt: d
    data: [  0.99990405, -0.00210801, 0.01369108, 0.07187873,
             0.0020542 ,  0.99999012, 0.00394316, 0.0043258, 
            -0.01369925, -0.00391466, 0.9998985, 0.03062641,
             0., 0., 0., 1. ]


#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.283          # accelerometer measurement noise standard deviation. #0.2   0.04
acc_w: 0.00212        # accelerometer bias random work noise standard deviation.  #0.002
gyr_n: 0.006463      # gyroscope measurement noise standard deviation.     #0.05  0.004
gyr_w: 0.0000267      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8         # gravity magnitude

#unsynchronization parameters
estimate_td: 0.0022406970325911093         # online estimate time offset between camera and imu
td: 0 # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 0                      # save image in pose graph for visualization prupose; you can close this function by setting 0 
