%YAML 1.0
---
#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1
num_of_cam: 2

imu_topic: "/cam_base/imu"
image0_topic: "/cam_EE/cam_base/image_rect_raw"
image1_topic: "/cam_EE/cam_base/image_rect_raw"
output_path: "output/"

cam0_calib: "left_base.yaml"
cam1_calib: "right_base.yaml"
image_width: 1280
image_height: 720

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2: unknown, auto-calib on-fly

body_T_cam0: !!opencv-matrix
    rows: 4
    cols: 4
    dt: d
    data: [  0.99986109, 0.00280214,  0.01643041, -0.02851038,
            -0.00272208, 0.99998432,  -0.0048932, -0.00111322,
            -0.01644386, 0.0048478 ,  0.99985304, 0.0216706 ,
             0., 0., 0., 1.]

body_T_cam1: !!opencv-matrix
    rows: 4
    cols: 4
    dt: d
    data: [  0.99984578, 0.00308292, 0.01728917, 0.06646931,
            -0.00297813, 0.99997706, -0.00608355, -0.00068148,
            -0.01730753, 0.00603112, 0.99983202, 0.02236662,
             0., 0., 0., 1.]


#Multiple thread support
multiple_thread: 1

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.176           # accelerometer measurement noise standard deviation. #0.2   0.04
acc_w: 0.008         # accelerometer bias random work noise standard deviation.  #0.002
gyr_n: 0.029          # gyroscope measurement noise standard deviation.     #0.05  0.004
gyr_w: 0.0001655        # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.8         # gravity magnitude

#unsynchronization parameters
estimate_td: 0.0025255259907404517          # online estimate time offset between camera and imu
td: 0 # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 0                      # save image in pose graph for visualization prupose; you can close this function by setting 0 
