%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
projection_parameters:
    fx: 905.930419921875
    fy: 905.91552734375
    cx: 652.3206176757812
    cy: 350.43377685546875

####### L515 #######
# distortion_model: "plumb_bob"
# D: [0.16681678593158722, -0.515194833278656, -0.0029630311764776707, 0.0005931710475124419, 0.47206392884254456]
# For "plumb_bob", the 5 parameters are: (k1, k2, t1, t2, k3).

# K: [905.930419921875, 0.0, 652.3206176757812, 0.0, 905.91552734375, 350.43377685546875, 0.0, 0.0, 1.0]
#     [fx  0 cx]
# K = [ 0 fy cy]
#     [ 0  0  1]

# float64[9]  R # 3x3 row-major matrix
# R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
# Rectification matrix (stereo cameras only)
# A rotation matrix aligning the camera coordinate system to the ideal
# stereo image plane so that epipolar lines in both stereo images are
# parallel.

# P: [905.930419921875, 0.0, 652.3206176757812, 0.0, 0.0, 905.91552734375, 350.43377685546875, 0.0, 0.0, 0.0, 1.0, 0.0]
# Projection/camera matrix
#     [fx'  0  cx' Tx]
# P = [ 0  fy' cy' Ty]
#     [ 0   0   1   0]


# Given a 3D point [X Y Z]', the projection (x, y) of the point onto
#  the rectified image is given by:
#  [u v w]' = P * [X Y Z 1]'
#         x = u / w
#         y = v / w
#  This holds for both images of a stereo pair.
# binning_x: 0
# refer to http://docs.ros.org/en/noetic/api/sensor_msgs/html/msg/CameraInfo.html